"""first

Revision ID: 26f71da72e23
Revises: 
Create Date: 2023-02-18 14:42:09.889374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26f71da72e23'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'document', ['id'])
    op.create_unique_constraint(None, 'email_creds', ['id'])
    op.create_unique_constraint(None, 'event', ['id'])
    op.create_unique_constraint(None, 'template', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    op.create_unique_constraint(None, 'vacancy', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vacancy', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'template', type_='unique')
    op.drop_constraint(None, 'event', type_='unique')
    op.drop_constraint(None, 'email_creds', type_='unique')
    op.drop_constraint(None, 'document', type_='unique')
    # ### end Alembic commands ###
